name: Release

on:
  release:
    types: [published]

jobs:
  sign-release:
    runs-on: ubuntu-latest
    name: Sign release and generate checksum
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Download source
        run: curl -sL "${{ github.event.release.tarball_url }}" >"$ARCHIVE_NAME".tar.gz

      - name: Create checksum
        run: sha256sum "$ARCHIVE_NAME".tar.gz > ${{ env.ARCHIVE_NAME }}-sha256-checksum.txt

      # Upload the checksum file so that it can be reused in the next job
      - uses: actions/upload-artifact@v2
        with:
          name: checksum-file
          path: ${{ env.ARCHIVE_NAME }}-sha256-checksum.txt

      - name: Sign archive
        run: gpg --armor --detach-sign "$ARCHIVE_NAME".tar.gz

      - name: Upload signature
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}.tar.gz.asc
          asset_name: ${{ env.ARCHIVE_NAME }}.tar.gz.asc
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload archive
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_name: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload checksum
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}-sha256-checksum.txt
          asset_name: ${{ env.ARCHIVE_NAME }}-sha256-checksum.txt
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ github.token }}
  release:
    needs: sign-release
    runs-on: ubuntu-latest
    name: Deploy release
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: ./.github/workflows/yarn

      - uses: ./.github/workflows/build
        with:
          secrets: ${{ toJSON(secrets) }}
          prod: ${{ true }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/download-artifact@v2
        with:
          name: checksum-file

      # Script to upload release files
      - name: 'Upload release build files for production'
        env:
          BUCKET: s3://${{ secrets.AWS_STAGING_BUCKET_NAME }}/releases/${{ github.event.release.tag_name }}
          CHECKSUM_FILE: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-sha256-checksum.txt
        run: bash ./scripts/github/s3_upload.sh

      # Script to prepare production deployments
      - run: bash ./scripts/github/prepare_production_deployment.sh
        env:
          PROD_DEPLOYMENT_HOOK_TOKEN: ${{ secrets.PROD_DEPLOYMENT_HOOK_TOKEN }}
          PROD_DEPLOYMENT_HOOK_URL: ${{ secrets.PROD_DEPLOYMENT_HOOK_URL }}
          VERSION_TAG: ${{ github.event.release.tag_name }}
