name: e2e

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: Smoke E2E tests
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/yarn

      - name: Install Cypress
        run: |
          ./node_modules/.bin/cypress install

      - uses: ./.github/workflows/build
        with:
          secrets: ${{ toJSON(secrets) }}
          e2e_mnemonic: ${{ secrets.NEXT_PUBLIC_CYPRESS_MNEMONIC }}

      - name: Serve
        run: yarn serve &

      - uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/smoke/*.cy.js
          browser: chrome
          record: true
          config: baseUrl=http://localhost:8080
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
