name: Mobile Tests and Coverage

on:
  push:
    branches:
      - main
    paths:
      - apps/mobile/**
  pull_request:
    paths:
      - apps/mobile/**

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0' # jod
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Run tests with coverage
      - name: Run Jest tests with coverage
        run: |
          yarn workspace @safe-global/mobile test:coverage --coverageReporters=text --coverageReporters=json-summary | tee ./coverage.txt && exit ${PIPESTATUS[0]}

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          coverage-title: Coverage
          coverage-path: ./coverage.txt
