name: Safe Apps e2e

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: Cypress Safe Apps tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@v1

      - uses: ./.github/workflows/yarn

      - name: Install Cypress
        run: |
          ./node_modules/.bin/cypress install

      - uses: ./.github/workflows/build
        with:
          secrets: ${{ toJSON(secrets) }}
          e2e_mnemonic: ${{ secrets.NEXT_PUBLIC_CYPRESS_MNEMONIC }}

      - name: Serve
        run: yarn serve &

      - uses: cypress-io/github-action@v4
        with:
          parallel: true
          spec: cypress/e2e/safe-apps/*.cy.js
          browser: chrome
          record: true
          config: baseUrl=http://localhost:8080
          group: 'Safe Apps tests'
        env:
          CYPRESS_PROJECT_ID: okn21k
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SAFE_APPS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
