name: Safe Apps e2e

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    if: >
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'issue_comment' && 
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/run-action') && 
      (github.event.comment.author_association == 'COLLABORATOR' || 
      github.event.comment.author_association == 'MEMBER' || 
      github.event.comment.author_association == 'OWNER'))
    runs-on: ubuntu-latest
    name: Cypress Safe Apps tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/yarn

      - name: Install Cypress
        run: |
          ./node_modules/.bin/cypress install

      - uses: ./.github/workflows/build
        with:
          secrets: ${{ toJSON(secrets) }}
          e2e_mnemonic: ${{ secrets.NEXT_PUBLIC_CYPRESS_MNEMONIC }}

      - name: Serve
        run: yarn serve &

      - uses: cypress-io/github-action@v4
        with:
          parallel: true
          spec: cypress/e2e/safe-apps/*.cy.js
          browser: chrome
          record: true
          config: baseUrl=http://localhost:8080
          group: 'Safe Apps tests'
        env:
          CYPRESS_PROJECT_ID: okn21k
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SAFE_APPS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
