name: Web Lint
on:
  pull_request:
    paths:
      - apps/web/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    permissions:
      checks: write
      pull-requests: read
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/yarn

      - uses: CatChen/eslint-suggestion-action@v4.1.7
        with:
          request-changes: true # optional
          fail-check: true # optional
          github-token: ${{ secrets.GITHUB_TOKEN }} # optional
          directory: './' # optional
          targets: '/apps/web/src' # optional
          config-path: './apps/web/eslint.config.mjs'
