name: Web Smoke tests

on:
  pull_request:
    paths:
      - apps/web/**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    name: Cypress Smoke tests

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cypress
        with:
          secrets: ${{ toJSON(secrets) }}
          spec: cypress/e2e/smoke/*.cy.js
          group: 'Smoke tests'
          tag: 'smoke'
