name: Web Production health check tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1-5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: Cypress production health check tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cypress
        with:
          secrets: ${{ toJSON(secrets) }}
          spec: |
            cypress/e2e/prodhealthcheck/*.cy.js
          group: 'Production health check tests'
          tag: 'production'

      - name: Python setup
        if: always()
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install junitparser
        if: always()
        run: |
          pip install junitparser

      - name: Merge JUnit reports for TestRail
        if: always()
        run: |
          junitparser merge --suite-name "Root Suite" --glob "apps/web/reports/junit-*" "apps/web/reports/junit-report.xml"

      - name: TestRail CLI upload results
        if: always()
        run: |
          pip install trcli
          if ! trcli -y \
          -h https://gno.testrail.io/ \
          --project "Safe- Web App" \
          --username ${{ secrets.TESTRAIL_USERNAME }} \
          --password ${{ secrets.TESTRAIL_PASSWORD }} \
          parse_junit \
          --title "Production Health Checks Automated Tests, branch: ${GITHUB_REF_NAME}" \
          --run-description ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
          -f "apps/web/reports/junit-report.xml"; then
            echo -e "\e[41;32mTestRail upload failed. Pipeline will continue, please check the upload process.\e[0m"
          fi
